### ISSUE TITLE
Weird styling for specializations while in GM-mode

### ISSUE THREAD

**Issue by TerraDOOM** [AI-Safety-Camp-Tabletop-RPG/companion-app#34]
While in GM-mode, there's a strange quirk in which edit/delete buttons on a specialization are only shown when hovering over the element, but showing these overflows the box causing the entire view to shift.

Steps to reproduce:
- Make a specialization
- Enter GM-mode
- Enter the specialization menu
- Hover over a specialization

As a quick hack, I added a new rule to just set `visibility: hidden` while not hovered, and adding in the `display: inline-block`.

```css
.group:not(:hover) .group-hover\:inline-block {
    display: inline-block;
    visibility: hidden;
}
```

Probably, you just want to make the element always inline-block and only use
```css
.group:not(:hover) .group-hover\:inline-block {
    visibility: hidden;
}
```
Alt
```css
.group:hover .group-hover\:inline-block {
    visibility: visible;
}
```
Or somesuch. I'm not an experienced frontend dev, so YMMV.
